M48
; DRILL file {KiCad (6.0.0-0)} date Sunday, 24 September 2023 at 20:44:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-24T20:44:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X22.86Y-22.86
X22.86Y-58.42
X137.16Y-22.86
X137.16Y-58.42
T0
M30
